In [1]:
import pandas as pd

* Main types:

In [17]:
# Series= 1-Dimensional
series = pd.Series(["BMW","TOYOTA","HONDA"])
series

0       BMW
1    TOYOTA
2     HONDA
dtype: object

In [18]:
colours = pd.Series(["Red","Blue","White"])
colours

0      Red
1     Blue
2    White
dtype: object

In [19]:
# Dataframe = two-dimensional

car_data = pd.DataFrame({"car make": series, "Colour": colours})
car_data

  car make Colour
0      BMW    Red
1   TOYOTA   Blue
2    HONDA  White

In [20]:
# Import Data [DataFrame]
car_sales = pd.read_csv('car-sales.csv')
car_sales.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [23]:
# Exporting a dataframe (Different dataset)
car_sales.to_csv("exported-car-sales.csv", index = False)

In [22]:
export_car_sales = pd.read_csv("exported-car-sales.csv")
export_car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

#### We looked at the main takeaways from this is that Pandas have two main data types:

* Series: Which is a one dimensional column.
* DataFrame: which is far more common type, which is two dimensional size.

# Introduction To Pandas

* Describe data using Pandas

In [ ]:
car_data.

* Don't forget to use this feature. when you applying any funcion you will get a all function list. so try I all as per you information
`abs`,`add`,`add_prefix`...

<img src="info.png" alt="info" />