In [1]:
# Import the data
import pandas as pd

In [2]:
car_sales = pd.read_csv('car-sales.csv')

In [3]:
car_sales.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [4]:
# to check bottom 5 rows
car_sales.tail(5)

     Make Colour  Odometer (KM)  Doors      Price
5  Toyota  Green          99213      4  $4,500.00
6   Honda   Blue          45698      4  $7,500.00
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

In [5]:
# any number you want to check 
car_sales.head(4)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00

.loc and .iloc

In [11]:
animals = pd.Series(["cat","dog","bird","pandas","snake"], index = [0,5,4,6,5])
animals

0       cat
5       dog
4      bird
6    pandas
5     snake
dtype: object

In [12]:
# Let's check with loc, it refers to index numbers
animals.loc[5] # In full form of loc in location, we will get elements at index 3

5      dog
5    snake
dtype: object

In [15]:
animals.loc[4] # bird at index 4

'bird'

In [16]:
# let with our dataset
car_sales.head

<bound method NDFrame.head of      Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00>

In [17]:
car_sales.loc[3]

Make                    BMW
Colour                Black
Odometer (KM)         11179
Doors                     5
Price            $22,000.00
Name: 3, dtype: object

In [20]:
animals

0       cat
5       dog
4      bird
6    pandas
5     snake
dtype: object

In [23]:
# let's try .iloc, I loc refers to position
animals.iloc[3] # if you count rows on the 3rd row you will get `pandas`

'pandas'

In [24]:
car_sales.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [26]:
# .iloc refers to index
car_sales.iloc[3]

Make                    BMW
Colour                Black
Odometer (KM)         11179
Doors                     5
Price            $22,000.00
Name: 3, dtype: object

* slicing

In [28]:
car_sales.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [30]:
car_sales.iloc[:3] # to get out data's first 3 rows

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
1   Honda    Red          87899      4  $5,000.00
2  Toyota   Blue          32549      3  $7,000.00