In [39]:
import pandas as pd

* Main types:

In [40]:
# Series= 1-Dimensional
series = pd.Series(["BMW","TOYOTA","HONDA"])
series

0       BMW
1    TOYOTA
2     HONDA
dtype: object

In [41]:
colours = pd.Series(["Red","Blue","White"])
colours

0      Red
1     Blue
2    White
dtype: object

In [42]:
# Dataframe = two-dimensional

car_data = pd.DataFrame({"car make": series, "Colour": colours})
car_data

  car make Colour
0      BMW    Red
1   TOYOTA   Blue
2    HONDA  White

In [43]:
# Import Data [DataFrame]
car_sales = pd.read_csv('car-sales.csv')
car_sales.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [44]:
# Exporting a dataframe (Different dataset)
car_sales.to_csv("exported-car-sales.csv", index = False)

In [45]:
export_car_sales = pd.read_csv("exported-car-sales.csv")
export_car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

#### We looked at the main takeaways from this is that Pandas have two main data types:

* Series: Which is a one dimensional column.
* DataFrame: which is far more common type, which is two dimensional size.

# Introduction To Pandas

* Describe data using Pandas

In [46]:
car_sales.head() # you will get top 5 rows with .head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [47]:
car_sales.head(10) # when you mension 10, you will get top 10 rows with .head(10)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

* Don't forget to use this feature. when you applying any funcion you will get a all function list. so try I all as per you information
`abs`,`add`,`add_prefix`...

<img src="info.png" alt="info" />

In [48]:
# check the data type 
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

You might notice the above code has () `bracket` after head like `car_sales.head(10)` 

 but for dtype don't have () bracket? `car_sales.dtypes`  So Why?

In [49]:
# Because this is a Attribute 
car_sales.dtypes
# It is just meta data which is stored about the car sales data frame

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

In [36]:
# Where as a function we use brackets
car_sales.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [51]:
# let's run other code 
car_sales.columns # to get column names

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [52]:
# Check indexes
car_sales.index

RangeIndex(start=0, stop=10, step=1)

In [54]:
# get the statistical infromation from the data
car_sales.describe() # make sure that describe only works on numerical coulmns

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [55]:
car_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     object
 1   Colour         10 non-null     object
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

<img src="data_img.png" alt="info" />

 add info